// proxy.js
export default {
  async fetch(request) {
    const url = new URL(request.url)
    const binId = url.searchParams.get("683061b78960c979a5a01dba") || "TVUJ_JSONBIN_ID"
    const method = request.method
    const apiKey = "$2a$10$qNV2tGipYXuFW3167xxgveC1QFEU7D.1fB.aARUKWmvB2htsyVee6" // NEUKLÁDEJ DO FRONTENDU

    const endpoint = `https://api.jsonbin.io/v3/b/${binId}`
    const headers = {
      "X-Master-Key": apiKey,
      "Content-Type": "application/json"
    }

    const init = {
      method,
      headers
    }

    if (method !== "GET") {
      init.body = await request.text()
    }

    const response = await fetch(endpoint, init)
    const data = await response.text()

    return new Response(data, {
      status: response.status,
      headers: {
        "Access-Control-Allow-Origin": "*",
        "Content-Type": "application/json"
      }
    })
  }
}
